remove unsafe code from read_into
RoccoDev/recordkeeper pull request #4
Opened 2024-01-03 15:07 UTC by ScanMountGoat

This PR removes the unsafe code from the read functions by working with references instead of pointers. The only remaining usafe code for reading is allocating an uninitialized `SaveData` on the heap and converting to a mutable reference. It should be doable to completely remove the unsafe code by putting the arrays on the heap with Box, but the changes would be more involved. Let me know if you have any comments or concerns.

2024-01-03 21:51 UTC, RoccoDev requested changes

2024-01-03 21:51 UTC, RoccoDev commented on lib/src/lib.rs
> +            SaveData::read_into(bytes, save.assume_init_mut())?;
If I'm reading this right, the docs for [assume_init_mut](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.assume_init_mut) state that calling the function before the struct is initialized is undefined behavior, even when the returned reference is used to initialize the struct.

As `read_into` is what initializes `SaveData`, the struct is not initialized yet when `assume_init_mut` is called.

2024-01-03 22:44 UTC, ScanMountGoat commented on lib/src/lib.rs
> +            SaveData::read_into(bytes, save.assume_init_mut())?;
That seems right. Isn't that what the previous code was already doing with as_mut_ptr? I'm not sure how you could safely store the save data in a single heap allocation unless you zero initialized it. 

I would like to completely remove the unsafe and just heap allocate the individual arrays with box, but I wanted to get your thoughts on it first. The read functions would return a value for initializing a single field instead of modifying an existing struct in that case.

2024-01-04 02:20 UTC, RoccoDev commented on lib/src/lib.rs
> +            SaveData::read_into(bytes, save.assume_init_mut())?;
With `as_mut_ptr`, behavior is only undefined when the pointer is read from. This requirement was passed down to `read_into` implementations as you can see from the docs. The MaybeUninit docs recommend using `as_mut_ptr` and the `addr_of_mut` macro to initialize a struct field-by-field.

Making multiple allocations for arrays could work to reduce the size of the main struct (which is the reason why I'm forcing the heap allocation for it, as wasm has a strict limit on stack size), originally I figured that since I'm allocating anyway I might as well make a single allocation and keep everything together. The current approach has some advantages though, for example some nested read calls (e.g. arrays of trivial structs, or arrays of arrays) compile to a single memcpy.

2024-01-04 02:32 UTC, ScanMountGoat commented on lib/src/lib.rs
> +            SaveData::read_into(bytes, save.assume_init_mut())?;
I can try and remove the unsafe completely in another commit. I wouldn't expect the performance to be noticeably different if you're already using byteorder. It's probably not worth making assumptions about endianness to optimize reading a few MB of data.

2024-01-04 03:11 UTC, ScanMountGoat commented on lib/src/lib.rs
> +            SaveData::read_into(bytes, save.assume_init_mut())?;
Reading over the Rust docs, it doesn't look like there's a way to get mutable references to uninitialized memory without UB. I'll go ahead and try the safe version and compare the performance.

2024-01-04 15:45 UTC, ScanMountGoat commented
I've update the read code to only use safe code. Performance has only regressed slightly from 1 ms to 4.3 ms on my machine. The array handling is pretty naive, so this can probably be optimized later.

```rust
static SRC: &[u8] = include_bytes!("../tests/res/save-ch5-v10.sav");

fn main() {
    let start = std::time::Instant::now();
    let mut save = recordkeeper::SaveFile::from_bytes(SRC).unwrap();
    save.write().unwrap();
    println!("{:?}", start.elapsed());
}
```

2024-01-04 22:17 UTC, RoccoDev requested changes
I left some comments on design and implementation details.

There's also an issue with how arrays are read, it seems. In the webapp, the Characters tab errors out due to an indexing error, and the Ouroboros tab has incorrect data. 
I think this has to do with the fact that `<T as SaveBin>::read` (especially for structs) does not "read" or advance the cursor after reading the last field, if there are unknown fields left (i.e. if cur_size < the size manually described by `#[size(S)]`), which would otherwise be accounted for in the old `[T; N]` implementation by iterating in steps of `S`. 

I would also still use slicing for `SaveBin::read` or a new cursor for each entry (though IIRC codegen wasn't very friendly with it), as failing to read an entry might leave the cursor in an invalid state.

I don't know whether you've managed to run the app, it should be enough to run `trunk serve` in the `webapp` directory, though you would need to install some tools on your system.

Alternatively, I also use a quick tester implementation that just uses Debug:

```rust
pub fn main() {
    let file =
        std::fs::read("/path/to/file.sav").unwrap();
    let save = SaveFile::from_bytes(&file).unwrap();
    println!("{:#?}", save.save());
}
```

2024-01-04 22:17 UTC, roccodev commented on lib/src/save/item/mod.rs
> +            ItemType::Cylinder => self.cylinders.deref(),
Minor stylistic choice, I prefer `&*` here over `.deref()`. It also removes the need to import the `Deref` trait directly.

2024-01-04 22:17 UTC, roccodev commented on lib/src/save/item/mod.rs
> +            ItemType::Cylinder => self.cylinders.deref_mut(),
Same as above, with `&mut *`

2024-01-04 22:17 UTC, RoccoDev commented on lib/src/util.rs
> +pub struct BoxArray<T, const N: usize> {
I would add an `into_raw(self) -> [T; N]` (or `into_inner` etc.) function to grab ownership of the entire array for one-shot operations.

Or even better I think, I've noticed that both `BoxArray<T, N>` and `Box<[T; N]>` are in use, and the two seem functionally equivalent. Then I think that `BoxArray<T, N>` could just be a type alias for `Box<[T; N]>`.

2024-01-04 22:17 UTC, RoccoDev commented on lib/src/util.rs
> +    T: SaveBin + std::fmt::Debug,
Instead of requiring a `Debug` implementation (which also needs to be propagated to extensions), I'd match on the result of `elements` with an `unreachable!()` (or a custom panic) for the else case. If I understand correctly, `Box<[T]> -> Box<[T; N]>` should only fail if the `[T]` doesn't hold exactly `N` elements, which isn't the case if all items were read.

2024-01-04 22:17 UTC, RoccoDev commented on lib/src/io.rs
> +pub trait OwnedSaveBin: SaveBin {
This trait is now equivalent to `SaveBin`, so it should be removed

2024-01-04 22:20 UTC, RoccoDev commented
Oh, also, I'm not sure about the `array_init` crate for that one array initialization. The crate uses `unsafe` internally, and since it'd be limited to that one call, I think I'd rather keep the old implementation, as it's much smaller to maintain compared to the external crate.

2024-01-04 23:02 UTC, ScanMountGoat commented
> Oh, also, I'm not sure about the `array_init` crate for that one array initialization. The crate uses `unsafe` internally, and since it'd be limited to that one call, I think I'd rather keep the old implementation, as it's much smaller to maintain compared to the external crate.

array_init is supposed to be a safe wrapper over the array initialization. For a manual impl with safe code, I think we would need to use try_into with a vec or default initialize the array. If you're fine with losing a small amount of performance, I can just read into a vec and use try_into to remove the array_init dependency.

> I think this has to do with the fact that <T as SaveBin>::read (especially for structs) does not "read" or advance the cursor after reading the last field

I thought I added that to the derive, but I can look into it. I should be able to just compare the debug output before and after the changes.

> failing to read an entry might leave the cursor in an invalid state

Shouldn't the read fail and return an error if any of the fields fail to read? Does calling code need the cursor to be in a particular state after the read fails? I'm assuming this is just an implementation detail for `SaveFile::from_bytes`.

2024-01-04 23:05 UTC, ScanMountGoat commented on lib/src/util.rs
> +pub struct BoxArray<T, const N: usize> {
The new type allows specializing the read impl for boxed arrays to avoid stack allocations. Another option is to only implement `SaveBin` for `Box<[T; N]>` and not `Box<T>`. We may not need to box single values if their arrays are already boxed.

2024-01-04 23:28 UTC, ScanMountGoat commented
The derived code is advancing the size, but the size calculation was wrong for some manual implementations. The debug output is the same now other than the new wrapper types, so it should be working now.

2024-01-05 19:54 UTC, RoccoDev requested changes
> If you're fine with losing a small amount of performance, I can just read into a vec and use try_into to remove the array_init dependency.

I would prefer that, please.

I think we're getting there, though I would also box the arrays in `MapBitmaps` (needs the `map-bitmaps` feature flag), as they cause a stack overflow in debug mode when enabled. Interestingly enough, map visibility data takes up more than 50% of the save file.

2024-01-05 19:54 UTC, RoccoDev commented on lib/src/save/flags.rs
> +struct ByteFlags<B: SaveBin + std::fmt::Debug, const N: usize>
The `Debug` bound isn't used outside of this struct, so it should be removed

2024-01-05 20:11 UTC, ScanMountGoat commented
> I would prefer that, please.

Sounds good. That should be all of the changes. Let me know if there are any more blocking issues before this can get merged.

2024-01-05 20:33 UTC, RoccoDev requested changes
Some unused imports are left, then it's ready to go.

2024-01-05 20:33 UTC, RoccoDev commented on lib/src/io.rs
> +use std::ops::Deref;
This import is unused

2024-01-05 20:33 UTC, RoccoDev commented on lib/src/util.rs
> +use std::ops::{Deref, DerefMut};
These imports are unused

2024-01-05 21:40 UTC, RoccoDev commented
Seems fine now, thanks for your interest in the project!

2024-01-05 21:41 UTC, merged